apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: service-front-grpc
spec:
  selector:
    matchLabels:
      app: service-front-grpc
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: service-front-grpc
    spec:
      containers:
      - name: node
        image: shahin/up-running-kub-grpc-front:d2f18a03d66fd5fa92f265b6503aea313dae1fde
        ports:
        - containerPort: 8000
        env:
          - name: "serviceAURL"
            value: "service-a-grpc-svc:80"
---
apiVersion: v1
kind: Service
metadata:
    name: service-front-grpc-svc
    labels:
        app: service-front-grpc
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 8000
      nodePort: 30002
    selector:
     app: service-front-grpc
