apiVersion: apps/v1 
kind: Deployment
metadata:
  name: service-a-grpc-mesh
spec:
  selector:
    matchLabels:
      app: service-a-grpc-mesh
  replicas: 4 
  template:
    metadata:
      labels:
        app: service-a-grpc-mesh
    spec:
      containers:
      - name: service-a-grpc-mesh
        image: shahin/up-running-kub-grpc:d2f18a03d66fd5fa92f265b6503aea313dae1fde
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
    name: service-a-grpc-mesh-svc
    labels:
        app: service-a-grpc-mesh
spec:
    clusterIP: None
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
    selector:
     app: service-a-grpc-mesh
    type: ClusterIP
