apiVersion: apps/v1 
kind: Deployment
metadata:
  name: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 4 
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: shahin/up-running-kub:d2f18a03d66fd5fa92f265b6503aea313dae1fde
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
    name: serice-a-svc
    labels:
        app: service-a
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
    selector:
     app: service-a
